"""
消费者故事原型 — 以 JTBD（Job / Step / Outcome / Force）为顶层，人口学与之绑定。
"""
from __future__ import annotations

from typing import Dict, List, Optional

PERSONA_ARCHETYPES: List[Dict] = [
    {
        "key": "spouse_pusher_liu",
        "seed_name": "刘女士",
        "segment": "关系驱动型",
        "role": "家人推动者(伴侣)",
        "subject": "丈夫(患者)",
        "stage": "察觉",
        "patient_severity": "中度",
        "dominant": ["A1", "B2", "B4"],
        "decision_style": "从众",
        "blockers": ["丈夫怕戴不住就放弃", "担心买贵被说乱花钱"],
        "drivers": ["分房压力", "先试后买", "面罩适配"],
        "jtbd": {
            "job_id": "J5",
            "job_owner": "伴侣",
            "entry_situation": "伴侣分房",
            "current_step_id": "f",
            "desired_outcome_ids": ["O4", "O3", "O8"],
            "forces": {
                "push": ["A1"],
                "pull": ["B4"],
                "anxiety": ["B2", "B11"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "丈夫鼾声越来越大，我们快要分房睡了，得帮他选一台能试戴、面罩合适的机器。",
            "fear": "最怕买了他戴不住，家里人更埋怨我瞎折腾。",
            "decision_logic": "先确认他愿意试，再比面罩和售后，价格要在家庭预算内。",
            "price_sensitivity": 6,
            "brand_anchor": "听朋友提过瑞思迈，但没实地比过",
            "channel_preference": "医院睡眠中心或能试戴的门店",
            "quote": "我不是不想买，是得先让他愿意戴，别又白花钱。",
        },
    },
    {
        "key": "spouse_shopkeeper",
        "seed_name": "吴姐",
        "segment": "经济受限型",
        "role": "家人推动者(伴侣)",
        "subject": "丈夫(患者)",
        "stage": "决策纠结",
        "patient_severity": "中度",
        "dominant": ["A1", "B8", "A9"],
        "decision_style": "谨慎",
        "blockers": ["总预算有限", "怕后续耗材贵"],
        "drivers": ["国补/优惠", "二手或租赁入门", "关系危机"],
        "jtbd": {
            "job_id": "J5",
            "job_owner": "伴侣",
            "entry_situation": "关系冲突/濒临破裂",
            "current_step_id": "e",
            "desired_outcome_ids": ["O4", "O6", "O8"],
            "forces": {
                "push": ["A1"],
                "pull": ["A7"],
                "anxiety": ["B8"],
                "habit_or_alternative": ["A9"],
            },
        },
        "mindset": {
            "core_motive": "老公打鼾全家睡不好，但家里开支紧，得找性价比高的方案。",
            "fear": "怕贪便宜买到翻新机，更怕隐藏费用超预算。",
            "decision_logic": "先算总账（机器+面罩+耗材），有补贴或试用才敢下单。",
            "price_sensitivity": 9,
            "brand_anchor": "国产也行，只要靠谱",
            "channel_preference": "京东自营或二手平台比价",
            "quote": "不是不买，是每一分钱都得花在刀刃上。",
        },
    },
    {
        "key": "spouse_lin",
        "seed_name": "林姐",
        "segment": "关系驱动型",
        "role": "伴侣(推动者)",
        "subject": "丈夫(患者)",
        "stage": "察觉",
        "patient_severity": "重度",
        "dominant": ["A1", "A5", "B2"],
        "decision_style": "理性",
        "blockers": ["丈夫抵触戴机", "女儿也被吵到"],
        "drivers": ["夜间窒息恐惧", "关系危机", "面罩舒适"],
        "jtbd": {
            "job_id": "J1",
            "job_owner": "伴侣",
            "entry_situation": "夜间憋醒",
            "current_step_id": "c",
            "desired_outcome_ids": ["O1", "O3", "O4"],
            "forces": {
                "push": ["A1", "A5"],
                "pull": ["B4"],
                "anxiety": ["B2"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "他夜间憋醒好几次，我也睡不踏实，再拖下去全家崩溃。",
            "fear": "最怕突然出事，也怕买了他坚持不了。",
            "decision_logic": "先让他承认问题严重，再选面罩舒适度口碑好的款。",
            "price_sensitivity": 5,
            "brand_anchor": "倾向进口大牌",
            "channel_preference": "医院推荐或旗舰店",
            "quote": "这事不能再拖了，但得选对才能戴得住。",
        },
    },
    {
        "key": "nurse_caregiver",
        "seed_name": "孙女士",
        "segment": "长期照护型",
        "role": "伴侣照护者",
        "subject": "丈夫(患者)",
        "stage": "就医确诊",
        "patient_severity": "中度",
        "dominant": ["A1", "B2", "B7"],
        "decision_style": "理性",
        "blockers": ["工作带娃忙，没时间反复试"],
        "drivers": ["渠道信任", "面罩适配", "医院同款"],
        "jtbd": {
            "job_id": "J5",
            "job_owner": "伴侣",
            "entry_situation": "伴侣长期失眠",
            "current_step_id": "d",
            "desired_outcome_ids": ["O4", "O3", "O7"],
            "forces": {
                "push": ["A1"],
                "pull": ["B4"],
                "anxiety": ["B2", "B7"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "我是护士，知道他需要规范治疗，但下班还要带娃，得选省心的方案。",
            "fear": "怕选错渠道买到水货，耽误治疗。",
            "decision_logic": "优先三甲或官方渠道，面罩必须试戴成功。",
            "price_sensitivity": 4,
            "brand_anchor": "瑞思迈或飞利浦",
            "channel_preference": "医院睡眠中心",
            "quote": "懂原理是一回事，回家能不能坚持是另一回事。",
        },
    },
    {
        "key": "filial_daughter",
        "seed_name": "小李",
        "segment": "长期照护型",
        "role": "子女(为父母)",
        "subject": "母亲(患者)",
        "stage": "决策纠结",
        "patient_severity": "中度",
        "dominant": ["A8", "A6", "B7"],
        "decision_style": "谨慎",
        "blockers": ["老人怕麻烦", "担心操作复杂"],
        "drivers": ["孝心", "共病担忧", "医院渠道"],
        "jtbd": {
            "job_id": "J7",
            "job_owner": "子女",
            "entry_situation": "父母打鼾憋气",
            "current_step_id": "e",
            "desired_outcome_ids": ["O5", "O1", "O2"],
            "forces": {
                "push": ["A8", "A6"],
                "pull": [],
                "anxiety": ["B7", "B3"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "母亲有高血压，医生提醒要查睡眠，我作为女儿得帮她把关。",
            "fear": "最怕老人坚持不了，买回去落灰。",
            "decision_logic": "先陪去医院确诊，选操作简单、售后上门的。",
            "price_sensitivity": 5,
            "brand_anchor": "医生推荐什么就倾向什么",
            "channel_preference": "三甲医院或官方门店",
            "quote": "给妈买东西，合适比便宜重要。",
        },
    },
    {
        "key": "filial_son",
        "seed_name": "韩女士",
        "segment": "长期照护型",
        "role": "子女(为父母)",
        "subject": "父亲(患者)",
        "stage": "就医确诊",
        "patient_severity": "中度",
        "dominant": ["A8", "B3", "B7"],
        "decision_style": "理性",
        "blockers": ["父亲倔强不愿戴", "两地奔波"],
        "drivers": ["孝心", "售后上门", "医院渠道"],
        "jtbd": {
            "job_id": "J7",
            "job_owner": "子女",
            "entry_situation": "老人健康担忧",
            "current_step_id": "d",
            "desired_outcome_ids": ["O5", "O7", "O1"],
            "forces": {
                "push": ["A8"],
                "pull": [],
                "anxiety": ["B3", "B7"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "父亲体检提示睡眠呼吸问题，我人在外地，得远程把设备与售后安排好。",
            "fear": "怕催得太紧伤感情，也怕买了没人教他用。",
            "decision_logic": "优先医院渠道+能上门/远程指导的售后。",
            "price_sensitivity": 4,
            "brand_anchor": "医院推荐",
            "channel_preference": "三甲+官方售后",
            "quote": "孝心不是买最贵，是买他能坚持用的。",
        },
    },
    {
        "key": "trucker_self",
        "seed_name": "王叔",
        "segment": "经济受限型",
        "role": "本人",
        "subject": "本人",
        "stage": "察觉",
        "patient_severity": "轻度",
        "dominant": ["A4", "A9", "B8"],
        "decision_style": "谨慎",
        "blockers": ["跑长途赚钱紧", "觉得戴机麻烦"],
        "drivers": ["白天嗜睡安全", "二手低门槛", "价格敏感"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "开车等红灯睡着",
            "current_step_id": "e",
            "desired_outcome_ids": ["O2", "O6", "O8"],
            "forces": {
                "push": ["A4"],
                "pull": [],
                "anxiety": ["B8"],
                "habit_or_alternative": ["A9"],
            },
        },
        "mindset": {
            "core_motive": "开车犯困太危险，但新机太贵，想看看二手或租赁。",
            "fear": "怕花大钱买了用不住，耽误跑活。",
            "decision_logic": "能试戴、总价低、售后清楚才考虑。",
            "price_sensitivity": 9,
            "brand_anchor": "国产性价比",
            "channel_preference": "二手平台或租赁",
            "quote": "我知道要重视，可也得看兜里有多少。",
        },
    },
    {
        "key": "young_pm",
        "seed_name": "小陈",
        "segment": "健康焦虑自用型",
        "role": "本人",
        "subject": "本人",
        "stage": "察觉",
        "patient_severity": "未确诊",
        "dominant": ["A2", "A3", "B5"],
        "decision_style": "理性",
        "blockers": ["还没正式确诊", "信息过载"],
        "drivers": ["手表预警", "医学数据恐惧", "品牌信任"],
        "jtbd": {
            "job_id": "J3",
            "job_owner": "本人",
            "entry_situation": "AHI/血氧确诊",
            "current_step_id": "a",
            "desired_outcome_ids": ["O1", "O2", "O7"],
            "forces": {
                "push": ["A2", "A3"],
                "pull": ["B1"],
                "anxiety": ["B5"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "手表提示血氧异常，查资料越查越怕，想确认要不要上呼吸机。",
            "fear": "怕延误治疗，也怕买错型号被割韭菜。",
            "decision_logic": "先做多导睡眠监测，再选数据口碑好的品牌。",
            "price_sensitivity": 5,
            "brand_anchor": "瑞思迈",
            "channel_preference": "互联网医疗+京东自营",
            "quote": "数据都红了，不能再当没事。",
        },
    },
    {
        "key": "doctor_self",
        "seed_name": "周医生",
        "segment": "健康焦虑自用型",
        "role": "本人",
        "subject": "本人",
        "stage": "就医确诊",
        "patient_severity": "中度",
        "dominant": ["A3", "A5", "B1"],
        "decision_style": "理性",
        "blockers": ["临床指标要求高", "时间少"],
        "drivers": ["AHI数据", "疗效可验证", "数据可见性"],
        "jtbd": {
            "job_id": "J3",
            "job_owner": "本人",
            "entry_situation": "最长呼吸暂停数十秒",
            "current_step_id": "m",
            "desired_outcome_ids": ["O1", "O2", "O7"],
            "forces": {
                "push": ["A3", "A5"],
                "pull": ["B1"],
                "anxiety": ["B3"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "自己AHI不低，知道规范治疗重要，会看临床数据和报告功能。",
            "fear": "怕设备数据不准，无法评估疗效。",
            "decision_logic": "参数、算法、报告完整性优先，其次才是价格。",
            "price_sensitivity": 3,
            "brand_anchor": "瑞思迈或飞利浦",
            "channel_preference": "医院渠道或官方",
            "quote": "治病的事，证据比广告重要。",
        },
    },
    {
        "key": "exec_self",
        "seed_name": "张先生",
        "segment": "健康焦虑自用型",
        "role": "本人",
        "subject": "本人",
        "stage": "决策纠结",
        "patient_severity": "重度",
        "dominant": ["A4", "A5", "B5"],
        "decision_style": "理性",
        "blockers": ["出差多", "担心便携性"],
        "drivers": ["白天安全", "进口品牌", "静音"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "开会打盹",
            "current_step_id": "d",
            "desired_outcome_ids": ["O2", "O3", "O6"],
            "forces": {
                "push": ["A4", "A5"],
                "pull": ["B10"],
                "anxiety": ["B5"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "开会打瞌睡太危险，体检也提示重度OSA，必须解决。",
            "fear": "怕影响工作和形象，也怕设备噪音大。",
            "decision_logic": "选进口旗舰+便携，出差也能用。",
            "price_sensitivity": 3,
            "brand_anchor": "瑞思迈",
            "channel_preference": "品牌官网或高端门店",
            "quote": "健康和工作，我都不想牺牲。",
        },
    },
    {
        "key": "retiree_struggle",
        "seed_name": "老马",
        "segment": "依从挣扎型",
        "role": "本人",
        "subject": "本人",
        "stage": "适应",
        "patient_severity": "中度",
        "dominant": ["B2", "B4", "B3"],
        "decision_style": "谨慎",
        "blockers": ["之前戴过不舒服", "面罩漏气"],
        "drivers": ["先试后买", "面罩适配", "售后保障"],
        "jtbd": {
            "job_id": "J1",
            "job_owner": "本人",
            "entry_situation": "睡眠碎片化",
            "current_step_id": "h",
            "desired_outcome_ids": ["O3", "O8", "O7"],
            "forces": {
                "push": [],
                "pull": ["B4"],
                "anxiety": ["B2", "B3", "B11"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "以前买过一台，面罩勒得难受就闲置了，想再试更合适的。",
            "fear": "怕又是买了落灰，浪费儿女的钱。",
            "decision_logic": "必须试戴成功+有人跟进售后，否则不买。",
            "price_sensitivity": 6,
            "brand_anchor": "无所谓品牌，舒服第一",
            "channel_preference": "能上门调试的门店",
            "quote": "不是不想戴，是上次那面罩真要命。",
        },
    },
    {
        "key": "roommate_young",
        "seed_name": "小杨",
        "segment": "关系驱动型",
        "role": "本人(室友影响)",
        "subject": "本人(受室友影响)",
        "stage": "未察觉",
        "patient_severity": "未确诊",
        "dominant": ["A1", "A4", "B8"],
        "decision_style": "冲动",
        "blockers": ["预算有限", "不确定该不该管室友的事"],
        "drivers": ["室友打鼾", "睡眠被影响", "价格"],
        "jtbd": {
            # 受害者叙事：要的是恢复自己的睡眠，不是「消除自己打呼丢人」
            "job_id": "J1",
            "job_owner": "本人",
            "entry_situation": "睡眠碎片化",
            "current_step_id": "a",
            "desired_outcome_ids": ["O1", "O3", "O6"],
            "forces": {
                "push": ["A1"],
                "pull": ["B4"],
                "anxiety": ["B8"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "合租室友鼾声如雷，我整夜睡不着，想推动他去筛查或自己想办法睡好。",
            "fear": "怕看了医生发现自己也要戴机，双重开销。",
            "decision_logic": "先弄清是他的问题还是我也有，再选低门槛方案。",
            "price_sensitivity": 8,
            "brand_anchor": "尚未形成偏好",
            "channel_preference": "线上比价",
            "quote": "被吵醒的日子受够了，得有个解决办法。",
        },
    },
    {
        # 真正的 J6：自己打呼丢脸
        "key": "shame_self",
        "seed_name": "小徐",
        "segment": "关系驱动型",
        "role": "本人",
        "subject": "本人",
        "stage": "察觉",
        "patient_severity": "轻度",
        "dominant": ["A11", "B6", "B8"],
        "decision_style": "谨慎",
        "blockers": ["觉得戴机丢人", "不想被同事知道"],
        "drivers": ["社交尊严", "体面外观", "入门价"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "宿舍/合租尴尬",
            "current_step_id": "c",
            "desired_outcome_ids": ["O1", "O5"],
            "forces": {
                "push": ["A11"],
                "pull": ["B6"],
                "anxiety": ["B8"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "自己打呼被室友录音嘲笑，想体面地解决，又不想闹得人尽皆知。",
            "fear": "最怕戴机更丢人，同事出差看见。",
            "decision_logic": "选小巧不显眼、有名人背书的入门方案。",
            "price_sensitivity": 7,
            "brand_anchor": "外观与口碑",
            "channel_preference": "线上匿名下单",
            "quote": "我不是不想治，是不想被当成笑话。",
        },
    },
    {
        "key": "elderly_self",
        "seed_name": "赵大爷",
        "segment": "长期照护型",
        "role": "本人",
        "subject": "本人",
        "stage": "就医确诊",
        "patient_severity": "中度",
        "dominant": ["A6", "B2", "B7"],
        "decision_style": "从众",
        "blockers": ["觉得戴机丢人", "操作怕复杂"],
        "drivers": ["共病担忧", "医院推荐", "面罩舒适"],
        "jtbd": {
            "job_id": "J3",
            "job_owner": "本人",
            "entry_situation": "高血压/心脏等共病",
            "current_step_id": "d",
            "desired_outcome_ids": ["O2", "O3", "O7"],
            "forces": {
                "push": ["A6"],
                "pull": [],
                "anxiety": ["B2", "B7"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "有高血压，医生说要治打鼾，儿子也催我去配机。",
            "fear": "怕给儿女添麻烦，也怕设备太复杂不会用。",
            "decision_logic": "听医生和儿子的，选操作简单、有人教的。",
            "price_sensitivity": 5,
            "brand_anchor": "儿子帮选",
            "channel_preference": "医院或儿子线上下单",
            "quote": "老了不怕花钱，怕不会用。",
        },
    },
    {
        "key": "als_caregiver",
        "seed_name": "陈女士",
        "segment": "长期照护型",
        "role": "子女(为父母)",
        "subject": "父亲(重症)",
        "stage": "就医确诊",
        "patient_severity": "重度",
        "dominant": ["A10", "B3", "B7"],
        "decision_style": "理性",
        "blockers": ["设备可靠性要求极高", "长期维护成本"],
        "drivers": ["呼吸支持", "远程照护", "售后上门"],
        "jtbd": {
            "job_id": "J4",
            "job_owner": "子女",
            "entry_situation": "ALS/渐冻症",
            "current_step_id": "j",
            "desired_outcome_ids": ["O9", "O7"],
            "forces": {
                "push": ["A10"],
                "pull": [],
                "anxiety": ["B3", "B7"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "父亲渐冻症需要夜间呼吸支持，这是保命设备，不能省。",
            "fear": "最怕机器失灵或没人指导，危及生命。",
            "decision_logic": "选医疗级、售后上门、能远程监护的方案。",
            "price_sensitivity": 2,
            "brand_anchor": "医院指定机型",
            "channel_preference": "医院渠道",
            "quote": "能多陪一天，就值。",
        },
    },
]


def pick_archetypes(
    count: int,
    *,
    job_ids: Optional[List[str]] = None,
    entry_situations: Optional[List[str]] = None,
) -> List[Dict]:
    """按 Job 轮询选取原型；人数超过原型数时复用（生成层负责换姓名）。"""
    import copy

    pool = PERSONA_ARCHETYPES[:]
    if job_ids:
        filtered = [a for a in pool if a.get("jtbd", {}).get("job_id") in job_ids]
        if filtered:
            pool = filtered
    if entry_situations:
        filtered = [
            a
            for a in pool
            if a.get("jtbd", {}).get("entry_situation") in entry_situations
            or any(
                e in (a.get("jtbd", {}).get("entry_situation") or "")
                for e in entry_situations
            )
        ]
        if filtered:
            pool = filtered

    if not pool:
        pool = PERSONA_ARCHETYPES[:]

    by_job: Dict[str, List[Dict]] = {}
    for a in pool:
        by_job.setdefault(a.get("jtbd", {}).get("job_id", "Jx"), []).append(a)
    keys = list(by_job.keys())
    chosen: List[Dict] = []
    si = 0
    while len(chosen) < count:
        key = keys[si % len(keys)]
        bucket = by_job[key]
        counts = {a["key"]: sum(1 for c in chosen if c.get("key") == a["key"]) for a in bucket}
        arch = min(bucket, key=lambda a: counts.get(a["key"], 0))
        chosen.append(copy.deepcopy(arch))
        si += 1
    return chosen[:count]
